import { ConnectButton } from "@rainbow-me/rainbowkit";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Vested App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className={styles.main}>
        <ConnectButton />

        <h1 className={styles.title}>
          Welcome to <a href="">Vested</a> <a href="">Token</a>{" "}
          <a href="">App!</a>
        </h1>

        <p className={styles.description}>
          Get started by deploying a dashboard{" "}
          <code className={styles.code}>for your organization</code>
        </p>

        <div className={styles.grid}>
          <a className={styles.card} href="https://github.com/dunnie99/Metacrafters">
            <h2>Vested App Documentation &rarr;</h2>
            <p>Learn about us.</p>
          </a>

          <a
            className={styles.card}
            href=""
          >
            <h2>Go to your dashboard &rarr;</h2>
            <p>Already have your dashboard?</p>
          </a>
          
          <Link className={styles.card} href="/createform">
            <h2>Deploy your dashboard &rarr;</h2>
            <p>Instantly deploy a vested token dashboard of your own</p>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
        <a href="https://linktr.ee/dun95" rel="noopener noreferrer" target="_blank">
          Made with ❤️ by Dunnie for MetaCrafters{" "}
        </a>
      </footer>
    </div>
  );
};

export default Home;
